import "oaidl.idl";
import "ocidl.idl";
import "unknwn.idl";

[
	object,
	uuid(093DC0FA-1054-4DCD-80EA-5E01C50D7400),
	helpstring("interface  IFileSystem implements common file operations")
]

interface IFileSystem : IUnknown
{
	HRESULT     MakeDirectory(long nX1);

	HRESULT     OpenFile(long nX2);
};

[
	uuid(3ff1aab8-f3d8-11d4-825d-00104b3646c0),
	helpstring("Imlementation for IFileSystem interface")
]
library FileSystemLib
{
	interface IFileSystem;
}